export const DATA_GET_SUCCESS = "DATA_GET_SUCCESS";
export const DATA_GET_FAILURE = "DATA_GET_FAILURE";

export const CATEGORIES_GET_SUCCESS = "CATEGORIES_GET_SUCCESS";
export const CATEGORIES_GET_FAILURE = "CATEGORIES_GET_FAILURE";
